// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ID          int32
	OrderID     int32
	Code        string
	Description string
	Quantity    int32
}

type Order struct {
	ID           int32
	CustomerName string
	OrderedAt    pgtype.Timestamp
}
